<a href="https://colab.research.google.com/github/Charleston9988/Charleston9988/blob/main/Code_(16th_Jan%2C_2022)_Loops_(For%2C_While)_If%2Celse%2C_elif_Others.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = 3
bin (x)
#converts the value to binary.
y = 8
z = 5
w = 9
~w
#this is a bitwise operator. It adds 1 to the value and makes it negative.
j = z | y
#This is a bitwise operator. It represents OR. 
k = z & x
#A bitwise operator. represents AND
g = z & y
p = w ^ z
#A bitwise operator. XOR.
m = w >> 1
# shifts the binary to the right. The first number by the left is removed
v = w << 1
#shifts the binary to the left. Zero is added to the last number by the right.

In [2]:
print (bin(x))
#Prints the binary value of x
print (bin(y))
print (bin(z))
print (bin(j))
print (j)
print (bin(k))
print (k)
print (bin(w))
print (~w)
print (p)
print (bin(p))
print (m)
print (bin(m))
print (v)
print (bin(v))

0b11
0b1000
0b101
0b1101
13
0b1
1
0b1001
-10
12
0b1100
4
0b100
18
0b10010


In [3]:
fearless_city_lodge = {"room_1": ["faithful" , "justin"], "room_2": "jojo", "room_8": "ben and vic", "room_7": "uganda babe", \
                      "room_6": "ik and halim", "room_3" : "the twins", "room_4": "sb and huncho", "room_5": "ng and ola"}

print (fearless_city_lodge["room_6"])
print ("room_3" in fearless_city_lodge)
if "jojo" in fearless_city_lodge:
    print (fearless_city_lodge)
else:
    print ("false")
if "ik" not in fearless_city_lodge:
    print ("True")
else:
    print ("false")

ik and halim
True
false
True


In [4]:
price = int(input("Enter price: "))
#int(input()) is used when the value changes. Input is then used to input recurring values.
qty = int(input("Enter qty: "))
amt = price * qty
if amt > 5000:
    print("10% is discounted")
    discount = amt * 10/100
    amt = amt - discount
else:
    print ("No discount")
print ("Amount payable:", amt)
#the if and else conditions. Do not forget ":" because it makes the argument valid.

Enter price: 6000
Enter qty: 50
10% is discounted
Amount payable: 270000.0


In [5]:
p = int(input("Flight fare: "))
# p = price
nop = int(input("NOP: "))
#number_of_passengers
tot = p * nop
#tot = total amount spent
if tot > 100000:
    print("The trip fare is expensive")
elif tot > 80000 and tot < 100000:
    print ("The trip fare is fair")
elif tot > 50000 and tot < 80000:
    print ("The trip fare is cheap but not very cheap")
else:
    print ("The trip fare is very cheap")

Flight fare: 50000
NOP: 60
The trip fare is expensive


In [6]:
practice = [20, 30, 35, 10, 58, 25]
print (practice)
for p in practice:
    print (p)


[20, 30, 35, 10, 58, 25]
20
30
35
10
58
25


In [7]:
while p > 5:
    p = p - 5
    print (p)

20
15
10
5


In [8]:
for b in range (10):
    print (b)
print ("'For' loops has finished!")
for h in range (1, 10):
    print (h)
print ("Range starts from 1")
for z in range (1, 10, 2):
    print (z)

0
1
2
3
4
5
6
7
8
9
'For' loops has finished!
1
2
3
4
5
6
7
8
9
Range starts from 1
1
3
5
7
9


In [9]:
practice = [20, 30, 35, 10, 58, 25]

sol = 0
ind = 0
while sol < 150:
    print (sol)
    sol = sol + practice [ind]
    ind = ind + 1


0
20
50
85
95


In [10]:
practice = [20, 30, 35, 10, 58, 25]

for i in practice:
    print (i)
    if i == 10:
        print ("The loop is stopped")
        break

20
30
35
10
The loop is stopped


In [11]:
ind = 0
while ind < len(practice):
    key = practice[ind]
    print (key)
    
    if key == 10:
        print ("Looped")
        break
    ind += 1
    

20
30
35
10
Looped


In [12]:
x = 2*2**3

print(x) 
no = " Hello World "
no.strip()
#used to remove whitespace at the beginning and end of a string
lst = [3,4,6,1,2]
lst[1:2] = [7,8]
print(lst)
youp = []*3
print (youp)

for num in range(2,-5,-1):

  print(num, end = ",")
#Another method of writing range


16
[3, 7, 8, 6, 1, 2]
[]
2,1,0,-1,-2,-3,-4,

In [13]:
numbers = [10, 20]

items = ["Chair", "Table"]

for x in numbers:

    for y in items:

        print(x, y)
    
for i in range(0,8):
    print (i)
    
hot = 0
while hot<7: 
    print ("good")
    hot+=1
for k in range (0, 5, 2):
    print (k)
print ("This is the first range")
for r in range (5, 0, -2):
    print (r)
print ("This is the second range")

car = 0
while car < 100 :
    car += 2
print (car)

10 Chair
10 Table
20 Chair
20 Table
0
1
2
3
4
5
6
7
good
good
good
good
good
good
good
0
2
4
This is the first range
5
3
1
This is the second range
100


In [14]:
Nigeria = {"Abia": "Umuahia", "Adamawa": "Yola", "Akwa-ibom": "Uyo"}

for key, value in Nigeria.items():
    print (key, "-", value)
#Looping for dictionaries. Use items to be able to loop the key and value.    

Nigeria ["Imo"] = "Owerri"
Nigeria ["Anambra"] = ["Wakwa", "Onitsha", "Awka", "Fezel", "Fegge"]
#Adding New entries in a Dictionary
print (Nigeria)

Nigeria["Anambra"].sort()
#sorts a list in the dictionary
print (Nigeria)

Nigeria["Anambra"].remove("Wakwa")
#Removes the value in the box() from the selected key
print (Nigeria)

Nigeria["Total"] = len(Nigeria)
print (Nigeria)

Nigeria["Total"] - 2
#Subtracts 2 from the value of Total
print (Nigeria)

Abia - Umuahia
Adamawa - Yola
Akwa-ibom - Uyo
{'Abia': 'Umuahia', 'Adamawa': 'Yola', 'Akwa-ibom': 'Uyo', 'Imo': 'Owerri', 'Anambra': ['Wakwa', 'Onitsha', 'Awka', 'Fezel', 'Fegge']}
{'Abia': 'Umuahia', 'Adamawa': 'Yola', 'Akwa-ibom': 'Uyo', 'Imo': 'Owerri', 'Anambra': ['Awka', 'Fegge', 'Fezel', 'Onitsha', 'Wakwa']}
{'Abia': 'Umuahia', 'Adamawa': 'Yola', 'Akwa-ibom': 'Uyo', 'Imo': 'Owerri', 'Anambra': ['Awka', 'Fegge', 'Fezel', 'Onitsha']}
{'Abia': 'Umuahia', 'Adamawa': 'Yola', 'Akwa-ibom': 'Uyo', 'Imo': 'Owerri', 'Anambra': ['Awka', 'Fegge', 'Fezel', 'Onitsha'], 'Total': 5}
{'Abia': 'Umuahia', 'Adamawa': 'Yola', 'Akwa-ibom': 'Uyo', 'Imo': 'Owerri', 'Anambra': ['Awka', 'Fegge', 'Fezel', 'Onitsha'], 'Total': 5}


In [15]:
a , b , c , d = 12 , 5 , 2, 9

if a + b == 17:
    print ("True")
else:
    print ("False")
print (a)
print (b)

for num in range (10,14):
    for i in range (2,num):
        if num % 2 == 1:
            print (num)
            break

True
12
5
11
13


In [16]:
var = 10
for i in range (10):
    for j in range (2,10,1):
        var % 2 == 0
        continue
        var += 1
    var += 1
else:
    var += 1
print (var)
d = {"john":40, "peter":45}
print (list(d.keys()))

21
['john', 'peter']


In [17]:
def display (s, n):
    print (s*n)
    
display ("trophy ", 3)


lis = [1,3,4]

r = sum(lis)
print (r)

trophy trophy trophy 
8


In [18]:
ju = [2,4,5]
t = sum(ju)
print (t)

11


In [19]:
from math import factorial
print (factorial(5))
#5!

120


In [20]:
import numpy as np
weights =np.array ([[50, 45, 56], [60,28,29], [49,20,28],
       [59, 90, 89],
       [ 70, 90, 89],
       [ 59, 90, 78], [59, 90, 89],
       [ 70, 90, 89],
       [ 59, 90, 78]])
weights = weights.reshape((3,3,3))
#Reshape. Can also be used to convert a One dimension array into 2 or more dimensions.
print (weights)
print (weights.ndim)
#Displays the dimension of the array
print (weights.tolist())
#Converts a Numpy array into a Python list

[[[50 45 56]
  [60 28 29]
  [49 20 28]]

 [[59 90 89]
  [70 90 89]
  [59 90 78]]

 [[59 90 89]
  [70 90 89]
  [59 90 78]]]
3
[[[50, 45, 56], [60, 28, 29], [49, 20, 28]], [[59, 90, 89], [70, 90, 89], [59, 90, 78]], [[59, 90, 89], [70, 90, 89], [59, 90, 78]]]


In [21]:
my_list = [ 1, 2, 3, 4, "stop", 5, 6]
for i in my_list:
    if i == ("stop"):
        print ("looped")
        break
    print (i)
#the break function

1
2
3
4
looped


In [22]:
my_list = [ 1, 2, 3, 4, "stop", 5, 6]
for i in my_list:
    if i == ("stop"):
        print ("looped")
        continue
    print (i)
#the continue function

1
2
3
4
looped
5
6


In [23]:
my_list = [ 1, 2, 3, 4, "stop", 5, 6]
for i in my_list:
    if i == ("stop"):
        print ("looped")
        
    print (i)
#the code without break or continue

1
2
3
4
looped
stop
5
6


In [24]:
list_ages = [10 , 11 , 19 , 7 , 8 , 24 , 91 , 74 , 25 , 53 , 41 , 50 , 63 , 86]
ages_even = []
for current_ages in list_ages:
    
    if current_ages % 2 == 1:
        continue
    ages_even.append(current_ages)
print (ages_even)

[10, 8, 24, 74, 50, 86]


In [25]:
list_1 = [1, 3, 6]
list_2 = [2, 5, 9]
zipped = zip(list_1, list_2)
print (list(zipped))
#the zip function

[(1, 2), (3, 5), (6, 9)]


In [26]:
list_3 = [1, 3, 6]
list_4 = [2, 5, 9]
for p,y in zip(list_3, list_4):
    print (p,y)

1 2
3 5
6 9


In [27]:
students_names = [ "Micheal Ford", "John Buch" , "Isra Raul", "Messi Ronaldo"]

students_grades = [ 80 , 53 , 90 , 100]

names_grades = {}
for s1, s2 in zip(students_names,students_grades):
    names_grades[s1] = s2
print (names_grades)
#Converting zip function to a dictionary

{'Micheal Ford': 80, 'John Buch': 53, 'Isra Raul': 90, 'Messi Ronaldo': 100}


In [28]:
list_3 = [1, 3, 6]
for m,n in enumerate(list_3):
    print (m,n)
#The enumerate function is a type of zip function but it takes only one argument
#It uses a counter(m) that keeps record. 

0 1
1 3
2 6


In [29]:
names = [ "Rachael Green", "Goodfellow Ian", "Tedd Crock", "Mina Joseph"]
salaries = [10260 , 41571 , 71211 , 52141 , 35781]
people_salaries = []

for n1,s1 in enumerate(names):
    x = s1 + ":" + " $"  + str(salaries[n1])
    people_salaries.append(x)

print (people_salaries)

['Rachael Green: $10260', 'Goodfellow Ian: $41571', 'Tedd Crock: $71211', 'Mina Joseph: $52141']


In [30]:
names = [ "Rachael Green", "Goodfellow Ian", "Tedd Crock", "Mina Joseph"]
salaries = [10260 , 41571 , 71211 , 52141, 9087987 ]
people_salaries = {}

for n1,s1 in zip(names, salaries):
    people_salaries[n1] = s1

print (people_salaries)

{'Rachael Green': 10260, 'Goodfellow Ian': 41571, 'Tedd Crock': 71211, 'Mina Joseph': 52141}


In [31]:
#Easier way of printing a list
list_com = [ i for i in range (1, 21) ]
print (list_com)

#instead of :
list_hard = []
for r in range (1, 21):
    list_hard.append(r)
print (list_hard)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [32]:
students_dict = { "Joel Corry" : 70, "James Bond" : 90, "Fatma Ahmed": 20, "Lily Saqr"  : 94, "Ahmed Yan"  : 40 }

passed_students_names = []
for keys, values in students_dict.items():
    if values < 50 :
        continue
    
    passed_students_names.append (keys)
print (passed_students_names)
#The continue function was used above. The keys for the values less than 50 ommitted.

passed_students_names = []
for keys, values in students_dict.items():
    
    if values > 50 :
        passed_students_names.append (keys)
print (passed_students_names)
#The keys for the values greater than 50 is displayed/printed

['Joel Corry', 'James Bond', 'Lily Saqr']
['Joel Corry', 'James Bond', 'Lily Saqr']


In [33]:
students_dict = { "Joel Corry" : 70, "James Bond" : 90, "Fatma Ahmed": 20, "Lily Saqr"  : 94, "Ahmed Yan"  : 40 }

passed_students_names = [ keys for keys, values in students_dict.items() if values > 50] 
print (passed_students_names)
#A shorter method of running the previous code

['Joel Corry', 'James Bond', 'Lily Saqr']


In [34]:
passed_students_names = [name.split()[0] for name, x in students_dict.items() if x > 50]
print (passed_students_names)
#The use of the .split() function seperates strings. [0] was then used to select the first name only.

['Joel', 'James', 'Lily']


In [35]:
def mult (x,y):
    res = x*y
    return res
#Defining a function using the return function
hji = mult (48,2)
print (mult (4,5))
print (hji)

def add (um, io):
    return um + io
result = add (4,5)
print (result)

20
96
9


In [36]:
students_names = [ "Micheal Ford", "John Buch" , "Isra Raul", "Messi Ronaldo"]

students_grades = [ 80 , 53 , 90 , 100]
def link_names_grades (students_names, students_grades):
    names_grades = {}
    for x , y in zip(students_names, students_grades):
        names_grades [x] = y
    return names_grades   
stu = ["obi", "tho"]
gra = [50, 80]
lo = link_names_grades (stu, gra)
print (lo)

{'obi': 50, 'tho': 80}


In [37]:
numbers = [10, 20 , 17 , 13 ]
even_or_odd = False
def filter_even_odd (numbers, even_or_odd):
    filtered_list = []
    
    for i in numbers:
        if i % 2 == even_or_odd:
            filtered_list.append(i)
    return filtered_list
filter_even_odd (numbers, even_or_odd)

[10, 20]

In [38]:
rest = 8
def add (um, io):
    rest = um +io
    return rest
hut = add (9,5)
print (hut)
print (rest)
print ("The First ends here")
#The intial value of rest(8) do not change because its a global variable while the rest in the function add its a local variable


rest = 8
def add (um, io):
    """
    The add function adds two variables together. Triple quotation is used to document strings
    """
    global rest
    rest = um +io
    return rest
hut = add (9,5)
print ("")
print (hut)
print (rest)
#Using the global function we are referring to the intial value of rest which is a global variable
#This alters the initial value of rest because it has been called in the add function where it takes a new command.

14
8
The First ends here

14
14
